export const TOGGLE_MD_TOOLBAR_VISIBLITY = 'toggle_md_config_visibility';
export const TOGGLE_SIDE_FOLD = 'toggle_sider_fold';
export const TOGGLE_MD_TOOLBAR_PIN = 'toggle_md_config_pin';
export const TOGGLE_MD_THEME = 'toggle_md_theme';
export const TOGGLE_MD_MODE = 'toggle_md_mode';
export const TOGGLE_MD_ICON = 'toggle_md_icon';
export const TOGGLE_MD_MATH = 'toggle_md_math';
export const TOGGLE_MD_AUTOSPACE = 'toggle_md_autospace';
export const TOGGLE_MD_PUNC = 'toggle_md_punc';
export const TOGGLE_MD_TOC = 'toggle_md_toc';
export const TOGGLE_MD_BEGSPACE = 'toggle_md_begspace';
export const TOGGLE_MD_HEIHLIGHT = 'toggle_md_high';
export const TOGGLE_MD_LINENUM = 'toggle_md_linenum';
export const CONFIG_INIT = 'config_init';

export const SET_ARTICLE = 'set_art';
export const CLEAR = 'clear';
export const CHANGE_TITLE = 'change';
export const UPDATE_CONTENT = 'update_con';
export const CREATE_FILE='create_file'
export const UPLOAD_LIST='upload_list'
